# Generated by Django 6.0.2 on 2026-02-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planmyevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requestquote',
            options={},
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='planmyevent',
            name='event_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='planmyevent',
            name='event_occasion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='planmyevent',
            name='expected_guests',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='planmyevent',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planmyevent',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planmyevent',
            name='theme_of_decor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='planmyevent',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='requestquote',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestquote',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestquote',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requestquote',
            name='service',
            field=models.CharField(max_length=200),
        ),
    ]
